[phases.setup]
nixPkgs = ["python3", "python3Packages.pip"]

[phases.build]
cmds = [
    "rm -rf backup",  # Elimina el directorio de backup
    "rm -rf 'copia de seguridad'",  # Elimina el directorio "copia de seguridad"
    "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py"